title: ENCODE Guidelines
email: federico.aurora@ub.uio.νο
github_username:  federicoaurora
# on desktop use: theme: bulma-clean-theme
# on gp use remote_theme: chrisrhymes/bulma-clean-theme 
remote_theme: chrisrhymes/bulma-clean-theme 
# theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme 
hide_footer: true
fixed_navbar: top
menubar: menu
hero_height: is-small
dropdown: is-active
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  


