title: ENCODE Guidelines
email: federico.aurora@ub.uio.νο
github_username:  federicoaurora
theme: bulma-clean-theme
hide_footer: true
fixed_navbar: top
menubar: menu
hero_height: is-small
dropdown: is-active
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  


